// apps/docs/src/examples/ProgressBarDemo.vue
<script setup lang="ts">
import { ref } from 'vue';
import { Checkbox, ProgressBar } from '@koyori-app/ui-vue';
import '@koyori-app/ui-vue/style.css';

const items = ['要件を書く', 'デザインを決める', '実装する', 'レビューを受ける', '公開する'];
const done = ref<string[]>([items[0]]);

function toggle(item: string, checked: boolean) {
  done.value = checked ? [...done.value, item] : done.value.filter(name => name !== item);
}
</script>

<template>
  <div style="display: grid; gap: 12px; max-width: 360px">
    <ProgressBar label="チェックリストの達成率" :value="done.length" :max="items.length"
      :value-text="`${done.length} / ${items.length} 件`" />
    <Checkbox v-for="item in items" :key="item" :label="item" :checked="done.includes(item)"
      :on-checked-change="(checked) => toggle(item, checked)" />
  </div>
</template>

// apps/docs/src/examples/ProgressBarDemo.tsx
import { useState } from 'react';
import { Checkbox, ProgressBar } from '@koyori-app/ui-react';
import '@koyori-app/ui-react/style.css';

const items = ['要件を書く', 'デザインを決める', '実装する', 'レビューを受ける', '公開する'];

export default function ProgressBarDemo() {
  const [done, setDone] = useState<string[]>([items[0]]);
  return <div style={{ display: 'grid', gap: 12, maxWidth: 360 }}>
    <ProgressBar label="チェックリストの達成率" value={done.length} max={items.length}
      valueText={`${done.length} / ${items.length} 件`} />
    {items.map(item => (
      <Checkbox key={item} label={item} checked={done.includes(item)}
        onCheckedChange={checked => setDone(checked ? [...done, item] : done.filter(name => name !== item))} />
    ))}
  </div>;
}
